In [2]:
"""list can be casted as numpy arr but it will produce a one dimensional 
array as we only have one list ."""
import numpy as np
my_list=[1,2,3]
arr=np.array(my_list)
print(arr)

[1 2 3]


In [1]:
np.arange(0,11,2)


NameError: name 'np' is not defined

In [5]:
np.ones((2,3))
#the [[]] in the output represents that the array/matrix is 2d 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:

np.zeros(3)

array([0., 0., 0.])

In [7]:
#gives indentity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
"""unlike previous function call we don,t need to us (()) for 2-d matrix , we can directly
assign the dimensions . In this case 5x5"""

np.random.rand(5,5)

array([[0.96867355, 0.98696044, 0.10623098, 0.82356069, 0.59969758],
       [0.47603707, 0.27668106, 0.33044517, 0.49548069, 0.94263691],
       [0.18826169, 0.05935649, 0.29620814, 0.76452201, 0.45848734],
       [0.15029813, 0.22647485, 0.59177604, 0.3745795 , 0.58967119],
       [0.63336504, 0.41285404, 0.90577955, 0.29527703, 0.2493196 ]])